// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.mail_checker = function(token, options) {
    var defaults, domain;
    if (typeof token === 'object') {
      options = token;
      token = null;
    }
    defaults = {
      token: null,
      trigger_on: "change",
      success: function() {},
      invalid_format: function() {},
      invalid_domain: function() {},
      temporary_mail: function() {},
      error: function(error) {
        return console.error(error);
      }
    };
    domain = document.domain.match(/([^.]+)\.[^.]+.?$/);
    if (domain && domain.length > 0) {
      domain = domain[0];
    }
    options = $.extend({}, defaults, options);
    if (!token) {
      token = options.token;
      if (!token) {
        console.error("Missing token parameter");
        return;
      }
    }
    return $(this).bind(options.trigger_on, function() {
      var data, _this;
      _this = this;
      data = {
        token: token,
        domain: domain,
        email: $(this).val()
      };
      return $.ajax({
        url: "http://www.mail-checker.com/check",
        data: data,
        dataType: "json",
        complete: function(jqXHR, textStatus) {
          if (jqXHR.status === 200) {
            options.success.apply(_this);
          }
          if (jqXHR.status === 422) {
            options.invalid_format.apply(_this);
          }
          if (jqXHR.status === 502) {
            options.invalid_domain.apply(_this);
          }
          if (jqXHR.status === 406) {
            options.temporary_mail.apply(_this);
          }
          if (jqXHR.status === 400) {
            return options.error.apply(_this, [$.parseJSON(jqXHR.responseText).error]);
          }
        }
      });
    });
  };

}).call(this);
